domain = 'cloudbearers.com'
IMAGE_NAME = "centos/7"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"+ '.' + domain
        master.vm.provision "file", source: "config", destination: "devops"
        master.vm.provision "shell", path: "shell/default-provision.sh"
        master.vm.provision "shell", path: "shell/k8s-bootstrap.sh"
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"+ '.' + domain
            node.vm.provision "file", source: "config", destination: "devops"
            node.vm.provision "shell", path: "shell/default-provision.sh"
            node.vm.provision "shell", path: "shell/k8s-bootstrap.sh"
        end
    end
end
