Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'linuxfoundation-centos.cloudbearers.com'
  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider :virtualbox do |vb|
       vb.memory = 2048

       vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
       vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
       vb.customize ["modifyvm", :id, "--groups", "/cloudbearers-devops"]
       vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]

  end

  config.vm.provision "shell", inline: <<-SHELL
     yum update -y
     yum install wget -y
  SHELL
end

