Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.hostname = 'linuxfoundation-ubuntu.cloudbearers.com'
  config.vm.network "private_network", ip: "192.168.33.30"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install wget -y
  SHELL
end
